# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Check build status

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /home/runner/work/LagGoggles/LagGoggles

    steps:
    - name: Checkout LagGoggles
      uses: actions/checkout@v2
      with:
        path: /home/runner/work/LagGoggles/LagGoggles

    - name: Checkout TickCentral
      uses: actions/checkout@v2
      with:
        repository: TerminatorNL/TickCentral
        path: /home/runner/work/LagGoggles/LagGoggles/TickCentral

    - name: Make gradlew executable (TC)
      run: chmod +x ./gradlew
      working-directory: /home/runner/work/LagGoggles/LagGoggles/TickCentral

    - name: Building TC
      run: ./gradlew setupCiWorkspace build publishToMavenLocal --console=plain
      working-directory: /home/runner/work/LagGoggles/LagGoggles/TickCentral
          
    - name: Verify gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Setup workspace
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: setupDecompWorkspace

    - name: Build jar
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
