# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle from the Gradle wrapper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup workspace
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: gradle/wrapper
        gradle-version: wrapper
        arguments: setupDecompWorkspace
    - name: Build FAT jar
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: gradle/wrapper
        gradle-version: wrapper
        arguments: build -PisFat
    - name: Build THIN jar
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-directory: gradle/wrapper
        gradle-version: wrapper
        arguments: build
